name: Attach test report

# Needs to be run separately because runs on external repositories can't add checks
on:
  workflow_run:
    workflows: [ "Pull Request Builds" ]
    types: [ completed ]

jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download Test Report
        uses: actions/download-artifact@v4
        with:
          name: gametest-results
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Attach Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: 'junit.xml'
          check_name: Gametest report
          summary: "Note that most functionality isn't currently tested by Gametest"
